# Copyright (C) 2013 Guenter Klambauer and Thomas Unterthiner
# <klambauer@bioinf.jku.at>

setGeneric("transcriptNames", function(object) 
			standardGeneric("transcriptNames"))
setGeneric("sampleNames", function(object) 
			standardGeneric("sampleNames"))
setGeneric("inputData", function(object) 
			standardGeneric("inputData"))
setGeneric("normalizedData", function(object) 
			standardGeneric("normalizedData"))
setGeneric("sizeFactors", function(object) 
			standardGeneric("sizeFactors"))
setGeneric("INIValues", function(object) 
			standardGeneric("INIValues"))
setGeneric("INIThreshold",function(object)
			standardGeneric("INIThreshold"))
setGeneric("INIThreshold<-",
		function(object,value)
			standardGeneric("INIThreshold<-")
)
setGeneric("INICalls", function(object) 
			standardGeneric("INICalls"))
setGeneric("pvals", function(object) 
			standardGeneric("pvals"))
setGeneric("responsibilities", function(object) 
			standardGeneric("responsibilities"))
setGeneric("posteriorProbs", function(object) 
			standardGeneric("posteriorProbs"))
setGeneric("logFC", function(object) 
			standardGeneric("logFC"))
setGeneric("conditionSizes", function(object) 
			standardGeneric("conditionSizes"))
setGeneric("sizeParameters", function(object) 
			standardGeneric("sizeParameters"))
setGeneric("means", function(object) 
			standardGeneric("means"))
setGeneric("dispersions", function(object) 
			standardGeneric("dispersions"))
setGeneric("params", function(object) 
			standardGeneric("params"))
setGeneric("INI", function(object,threshold=0.1) 
			standardGeneric("INI"))
setGeneric("sort")
setGeneric("as.data.frame")
